apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-pod-deployment
  namespace: dp-test
  labels:
    name: postgres-pod
    app: voting-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: voting-demo
  template:
    metadata:
      name: postgres-pod
      labels: 
        name: postgres-pod
        app: voting-demo
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432