apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: dp-test
  labels: 
    name: db-service
    app: voting-demo
spec:
  ports: 
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: voting-demo

