apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-result-deployment
  namespace: dp-test
  labels:
    name: voting-result
    app: voting-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-be-pod
      app: voting-demo
  template:
    metadata:
      name: result-app-pod
      labels: 
        name: voting-be-pod
        app: voting-demo
    spec:
      containers:
        - name: voting-be
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80