apiVersion: v1
kind: Pod
metadata:
  name: voting-fe-pod
  labels: 
    name: voting-fe-pod
    app: voting-demo
spec:
  containers:
    - name: voting-fe
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80
