apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels: 
    name: voting-be-pod
    app: voting-demo
spec:
  containers:
    - name: voting-be
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
